name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses : actions/checkout@v3
      -  name: echo
         run: |
          echo "hello1"
          echo "hello2"
  sleep:
    runs-on:  ubuntu-latest
    steps:
       - name: sleep
         run: sleep 20

      
